# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "#TCDX"
author: "Alex Gil"
email: colibri.alex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Our tenth anniversary conference dedicated to Caribbean digital studies.
baseurl: "/2023" # the subpath of your site, e.g. /blog
url: "http://caribbeandigitalnyc.net" # the base hostname & protocol for your site
twitter_username: elotroalex
github_username: elotroalex

permalink: pretty

collections:
  program:
    output: true

# Build settings
markdown: kramdown

# Markdown specs
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude: [RAKEFILE]
